### ISSUE TITLE
autopaho rpc example broken?

### ISSUE THREAD

**Issue by yogihardi** [eclipse/paho.golang#105]
**Describe the bug**
I am trying to run example of autopaho rpc (`autopaho/cmd/rpc`), but it returned the payload instead of the value.
seems like the example is broken or might be in autopaho itself.

**To reproduce**
* run `autopaho/cmd/rpc` code
* observe the output

**Debug output**
```
mqtt connection up
mqtt subscription made
2022/11/11 10:30:34 TEST
mqtt connection up
mqtt subscription made
2022/11/11 10:30:39 Received response: {"function":"mul", "param1": 10, "param2": 5}
2022/11/11 10:30:39 Received message with response topic client1/responses and correl id 1668137439126418000
{"function":"mul", "param1": 10, "param2": 5}
2022/11/11 10:30:39 Received message with response topic client1/responses and correl id 1668137439129025000
{"function":"mul", "param1": 10, "param2": 5}
2022/11/11 10:30:39 Received response: {"function":"mul", "param1": 10, "param2": 5}
2022/11/11 10:30:39 Received message with response topic client1/responses and correl id 1668137439131708000
{"function":"add", "param1": 5, "param2": 7}
2022/11/11 10:30:39 Received response: {"function":"add", "param1": 5, "param2": 7}
```

**Expected behaviour**
```
2022/11/11 10:30:39 Received message with response topic client1/responses and correl id 1668137439131708000
{"function":"add", "param1": 5, "param2": 7}
2022/11/11 10:30:39 Received response: {"value": 12}
```

**Software used:**
go version go1.17.6 darwin/amd64

**Comment by MattBrittan** [comment]
This took a while to trace :-).

You can fix it by adding `cliCfg.Router = paho.NewStandardRouter()` at [line 123 in main.go](https://github.com/eclipse/paho.golang/blob/master/autopaho/cmd/rpc/main.go#L123). 

The reason that this took a while is that this example needs work (it looks like when it was ported to autopaho a few bugs were introduced).  @bkneis  do you want to have a look at fixing this?

The issues I have spotted are:

# getCmConfig

Sets a callback function that subscribes to `cfg.topic`. Would not be an issue but you are using that config for both the client and server (which really confused me as I could not see where RPC was subscribing to that topic :-)  ).

Sets the Router is as follows:

`Router: paho.NewSingleHandlerRouter(func(m *paho.Publish) {
	log.Printf("%v+", m)
}),`

The SingleHandlerRouter does not support topics (all messages received are sent to the callback) and this will break the RPC handler (which trusts that the router will work per-topic). That works OK for the server but the client rpc functions expect to be able to filter by topic.

I suspect that the impact of this bug was seen during development as there are a few `time.Sleep`s that should not be needed (but I'm guessing were added  in an attempt to solve this).

**Comment by yogihardi** [comment]
thank you @MattBrittan for your response, but the solution you gave didn't worked 

> You can fix it by adding cliCfg.Router = paho.NewStandardRouter() at [line 123 in main.go](https://github.com/eclipse/paho.golang/blob/master/autopaho/cmd/rpc/main.go#L123).

**Comment by MattBrittan** [comment]
Just tried again with the change:

```
cliCfg := getCmConfig(cfg)
cliCfg.Router = paho.NewStandardRouter() // New line

listener(cfg.topic)
```

and the result was as expected:

```
2022/11/14 16:49:10 Received message with response topic client/responses and correl id 1668397750309492200
{"function":"mul", "param1": 10, "param2": 5}
2022/11/14 16:49:10 Received response: {"value":50}
2022/11/14 16:49:10 Received message with response topic client/responses and correl id 1668397750320836700
{"function":"mul", "param1": 10, "param2": 5}
2022/11/14 16:49:10 Received response: {"value":50}
2022/11/14 16:49:10 Received message with response topic client/responses and correl id 1668397750327385300
{"function":"add", "param1": 5, "param2": 7}
2022/11/14 16:49:10 Received response: {"value":12}
```

Note that as I mentioned there are a few issues with the code and this fix is a bit of a hack (my main aim was to confirm that the issue is with the rpc code rather than `autopaho` itself).
