### ISSUE TITLE
paho router's handler has no panic protection which leads to application crashing

### ISSUE THREAD

**Issue by dcl3** [eclipse/paho.golang#106]
**Is your feature request related to a problem? Please describe.**
Currently we are ingesting data through MQTT and when parsing the topic, we sometimes receive errors if the topic is formatted incorrectly. These errors crash the application and creates down time in our data ingestion where it receives no data

**Describe the solution you'd like**
We would like errors that occur in the handler to not stop the entire application and only terminate within the handler. This way we wouldn't have to worry about possible errors that could occur and our data ingestion can continue.

**Describe alternatives you've considered**
Currently we have added our own makeshift error handler that will just print out the logs when errors occur in our handlers.

**Comment by civilizeddev** [comment]
## Related

- https://github.com/eclipse/paho.golang/blob/master/paho/router.go#L97
- https://github.com/eclipse/paho.golang/blob/master/paho/router.go#L205

**Comment by MattBrittan** [comment]
>We would like errors that occur in the handler to not stop the entire application and only terminate within the handler.

By "errors" I am assuming that you mean panic's? (a properly handled error should not stop anything). You can prevent panics from stopping the program by [handling them](https://go.dev/ref/spec#Handling_panics) within the message handler (which is what I'm assuming you are doing?).

I would only expect panic to be called in ["truly exceptional conditions"](https://go.dev/doc/faq#exceptions). As such I'm not sure how the library could handle such events in a generic way. For example, I'd want an "out of memory" panic to crash the program (it's exceptional, I have no way to recover, and I don't want to acknowledge any more messages because doing so means they will probably be lost). The decision re how to deal with panics will depend on your specific circumstances which means, I think, that its best dealt with within your own code. This is something that is fairly simple to do (you could write a wrapper for your handlers that catch/log panics).

Apologies if I've misunderstood the issue; it would probably be beneficial if you could include more info and details as to how you propose panics should be dealt with.

**Comment by civilizeddev** [comment]
https://docs.gofiber.io/api/middleware/recover

```go
func (r *StandardRouter) Route(pb *packets.Publish) {
	...
	for route, handlers := range r.subscriptions {
		if match(route, topic) {
			r.debug.Println("found handler for:", route)
			for _, handler := range handlers {
				handler(m) // <-- can crash if a panic occurs.
			}
		}
	}
}
```

```go
func (s *SingleHandlerRouter) Route(pb *packets.Publish) {
	...
	s.handler(m) // <-- can crash if a panic occurs.
}
```

A topic handler function can crash by an unexpected panic.
In this case, only that handler call should fail, the whole app should not crash due to panic.

I propose something like a error hand option to prevent this.

### client.go

```go
func (c *Client) routePublishPackets() {
	defer func() {
		if r := recover(); r != nil {
			c.errors.Printf("failed to handle publish packet for %d: %s", pb.PacketID, err)
			c.OnError(r) // <-- the error handler function that can be defined in the config
		}
	}()
	
	...
	c.Router.Route(pb)
}
```

**Comment by MattBrittan** [comment]
Thanks for your example. I understand how you could recover from panics within `StandardRouter`, my question was more along the lines of "should we".

The issue with a solution such as you provided is that it would tend to hide panics from users (whom are unlikely to configure the `s.OnError` callback). We are also left in an uncertain state (should we ACK the message? if not it may be redelivered when we reconnect leading to a loop etc).

As such I believe that the current approach is probably the best default position (and is inline with the way stdlib http handlers work).

If you want to catch panics then you can use a custom router (as shown in your code; the `StandardRouter` is intended to meet basic needs and provide an example). Alternatively you can wrap your handlers with a `recover` which would provide more flexibility (how you recover from a panic may vary from handler to handler).

**Comment by MattBrittan** [comment]
I'm going to close this as a will not fix. 

I feel that there is a reasonable consensus that `panic` should only be used when something very unexpected happens that cannot be dealt with any other way (see supporting links below). Because of this we should not try to guess what a `panic` in a users handler function means; we have no way of knowing whether the users application is in a state from which recovery is possible (e.g. it may have called panic whilst holding a mutex). Recovering from the panic may leave things in a bad state; whereas if we allow the application to crash it can be restarted and, subject to config, the broker will retransmit any messages that have not been handled.

As such I feel that it's best that we allow the application to crash by default; if users wish to catch panics then they can do so (either in the handler or using a custom router).

### [Effective Go](https://go.dev/doc/effective_go#panic)

> But what if the error is unrecoverable? Sometimes the program simply cannot continue.

> For this purpose, there is a built-in function panic that in effect creates a run-time error that will stop the program (but see the next section).

>This is only an example but real library functions should avoid panic. If the problem can be masked or worked around, it's always better to let things continue to run rather than taking down the whole program. One possible counterexample is during initialization: if the library truly cannot set itself up, it might be reasonable to panic, so to speak. 

### Google [Go Style Decisions](https://google.github.io/styleguide/go/decisions#dont-panics) 

> Do not use panic for normal error handling.
> For errors that indicate “impossible” conditions, namely bugs that should always be caught during code review and/or testing, a function may reasonably return an error or call [log.Fatal](https://pkg.go.dev/github.com/golang/glog#Fatal).

### Uber [Go Style Guide](https://github.com/uber-go/guide/blob/master/style.md#dont-panic) 

>Panic/recover is not an error handling strategy. A program must panic only when something irrecoverable happens such as a nil dereference. An exception to this is program initialization: bad things at program startup that should abort the program may cause panic.
