### ISSUE TITLE
Make it easier for newcomers to understand the current state and history of this project

### ISSUE THREAD

**Issue by vishnureddy17** [eclipse/paho.golang#130]
My team is evaluating this project, as we have the desire for a MQTT 5 client in go for high availability applications. My understanding is that there are gaps, particularly the lack of a persistence/session store implementation, that make this project unsuitable for zero-message-loss applications. 

As a newcomer to this repository, I am having a hard time wrapping my head around the current state and history of this project. From my perspective, cleaning up the discussions floating around and adding more context around the current state of this project would help to move the project forward and attract contributors. My team may be willing to make contributions in the future (this is by no means a commitment), but it is difficult for us understand where the gaps are and where we could contribute.

Here are some actions I'm suggesting in order to improve this experience:
- Clean up and consolidate discussions in PRs and issues.
- Have a description of the history of this project. Maybe retroactively writing a changelog for previous versions could do this.
- Have clear documentation on the current limitations. Perhaps include estimates on the effort involved to fill in those gaps.
- Make it clear who the maintainers are. Right now, it seems like @MattBrittan is the main person active on this (apologies if I missed someone)

Thank you so much to all the maintainers and contributors!

**Comment by MattBrittan** [comment]
Welcome @vishnureddy17!

This project was started by @alsm and is very much his work. I added `autopaho` (as an attempt to make something user friendly enough for v3 users to migrate to) and have, recently, accepted a few PR's, and made a release, as I had been unable to make contact with @alsm. My main focus had been on the [v3 client](https://github.com/eclipse/paho.mqtt.golang) but I feel that this is now stable, and feature complete, so am not anticipating any major changes going forward. The v3 client API is a bit of a mess (for historical reasons; it's evolved over time and has way too many configuration options!) and this is one of the main reasons that @alsm started the v5 project from scratch (I really like the design!).

I have recently (last week) heard from @alsm and he indicated that he is going to put some time into looking at PR's and persistence. I will email him to draw his attention to this issue and hopefully we can start a discussion about the best way forward (there have been other contributors who may have opinions too!). 

I don't currently utilise this client myself due to the lack of full QOS1 support (Persistence) and this is one of the reasons I've not put much time into it. However I'm happy to dedicate some time to it if others are; implementing persistence is more complex than it sounds and something I feel is best approached in a collaborative manner. I've made a couple of attempts but was not happy with the designs (felt they added too much complexity) so scrapped them!

Anyway lets see what Al's thoughts are and, hopefully, we can move this forward together (I'm happy to start by updating the readme).

Cheers,
Matt

**Comment by alsm** [comment]
Thanks for your interest in the project, always keen to have more people looking to contribute. As Matt says I did most of the work on the core client. Having previously worked on the v3 client I was looking to develop something for v5 with a better, more idiomatic api. And one that would be designed to implement the spec but not necessarily replicate all the client function that the v3 client had. That functionality is where Matt's work on autopaho fits in, wrapping the core client  with something more familiar.

As Matt also identified the big sticking point for the v5 client now is implementing persistence, both he and I have had a look at the problem before and not really come up with something satisfactory, but it is the most pressing issue in my mind.

Beyond that I will look to put together a table of v5 spec features and their support or not in this client so we can present a clearer picture of the state and gaps in the client along with most information about the history etc. I have been lax in addressing issues and PRs for a while but am keen to put more in.

**Comment by alsm** [comment]
@vishnureddy17 an issue here to discuss it would be best I think. Look forward to hearing your thoughts.

**Comment by MattBrittan** [comment]
I opened [an issue](https://github.com/eclipse/paho.golang/issues/25) re persistence a couple of years ago that may be a good place (if Github issues is the right tool). As paho-dev goes to a large group, most of whom have no interest in Go, I'm not sure that is the right place. Another option would be the #MQTT topic on the Gophers Slack channel (53 members so probably gets more eyes than this repo - I rarely check it but if I know there will be a discussion there will do so more frequently).

**Comment by vishnureddy17** [comment]
Thanks! I'll open an issue with some thought. Closing this one.
