### ISSUE TITLE
Useless "use of closed network connection" error after autopaho disconnect

### ISSUE THREAD

**Issue by thejan2009** [eclipse/paho.golang#157]
**Describe the bug**
While working on #153, I started finding new errors in the log.

On latest master, I reliably get autopaho `OnClientError` even after legitimately disconnecting the client, the error says something like `read tcp 10.42.1.27:48018->18.196.199.37:443: use of closed network connection`

**To reproduce**
Create autopaho client with defined OnClientError, then connect and disconnect.

**Expected behaviour**
No error.

**Software used:**
I suspect this is the culprit https://github.com/eclipse/paho.golang/commit/c5d83b82693d45a7f9c8265fbbb3a4722ffa1f02/autopaho/auto.go#diff-c1ef7c1c120786f08491971c56e70b874f779e875fc0352a4085b3a9954a754cR195

What probably happened before is that the goroutine that sent this error was canceled before it could send the error through unbuffered channel. Now the channel is buffered so the error always arrives.

CC @MattBrittan

**Comment by MattBrittan** [comment]
Previously the `handleError` will have been blocked at `e.errChan <- err` because the channel was not ready to receive  (or, potentially, at `e.mu.Lock()` because a concurrent call to `handleError(err error)` was waiting on the channel). This lead to a goroutine leak which is, I believe, why the callbacks were not being called (there was nothing intentionally preventing this).

The way this is currently working (from the end users perspective) mirrors the `paho` library (which may well send multiple errors; this is why `errorHandler` is needed). This means it's not really a bug in `autopaho`, but I don't think it's expected behaviour either.

I have created a PR (#158) an would appreciate feedback on whether this is a reasonable approach.
