### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by princjef** [eclipse/paho.golang#223]
**Is your feature request related to a problem? Please describe.**
The LICENSE file for this repository contains the EPLv2 license, but there is also a DISTRIBUTION file that contains the EDLv1 license. Is it correct that this repository can be used under either the EPLv2 license or the EDLv1 license?

**Describe the solution you'd like**
If the repository can be used under either license, it would be nice to have that clarified in the LICENSE file, similar to what the paho.mqtt.golang repository has: https://github.com/eclipse/paho.mqtt.golang/blob/master/LICENSE

**Additional context**
A similar issue was opened against the paho.mqtt.golang repository and the LICENSE file was updated to clarify that the repository was dual-licensed: https://github.com/eclipse/paho.mqtt.golang/issues/191

**Comment by MattBrittan** [comment]
Looks like both documents were added when the project was created 6 years ago and have not been touched since. As such I'd say this is a question for @alsm.

I'd probably suggest we just delete DISTRIBUTION, as EPLv2 is fairly weak. Also I note that https://www.eclipse.org/org/documents/edl-v10.php states "Use of the Eclipse Distribution License by any project at the Eclipse Foundation must be reviewed and unanimously approved by the [Board of Directors](https://www.eclipse.org/org/foundation/directors.php)"...
