### ISSUE TITLE
Quality of current version

### ISSUE THREAD

**Issue by Tockra** [eclipse/paho.golang#23]
Hi,

I wanted to ask if the current version is stable?
I see you didn't changed something on that code for a while. 

I want to use a mqtt v5 client in my project. Currently I'm using: 
https://github.com/eclipse/paho.mqtt.golang
but for some mqtt v5 features I would replace the code. 

T

**Comment by alsm** [comment]
I've just made some performance improvements today, but I believe the code to be fairly stable. But it hasn't had sufficient real world use to know that it won't need changing. If you were to use this client I would appreciate feedback on how it works/feels to use.

**Comment by Tockra** [comment]
Can you place a documentation link somewhere?

**Comment by Tockra** [comment]
And maybe you could explain the idea of contexts. For example what does following lines?:

```go
ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
defer cancel()
_, err := mqttConnection.Publish(ctx, &content)
```

**Comment by justinclift** [comment]
@Tockra Contexts are used to add extra pieces of info, add signals (and more) to requests.  They're often used with HTTP(S) requests.  The initial explanation doc on the Go Blog gives a reasonable explanation:

&nbsp; &nbsp; https://blog.golang.org/context

That being said, they can add a bunch of extra complication to a codebase, and doesn't really seem to be needed for most applications I've personally seen so far.

**Comment by alsm** [comment]
There is also a memory based persistence implemented, there is not currently a file based implementation, the interface for Persistence is public (and so are all the ControlPacket structs) so implementing other persistence mechanisms shouldn't be too complicated.

The ReceiveMaximum (https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901049) is a value to indicate the maximum number of inflight QoS1/2 messages permitted.

There is no facility to check the connected status of the client, the API is designed as synchronous so if not connected Publish/etc. will return errors and there is an OnDisconnect callback for the client that is triggered if the server initiates a disconnect.

The contexts are used to allow you set timeouts (if desired) for functions, these only apply to the time spent waiting for a reply rather than the total time to run the function (for example if there is blocking in sending the packet, that time doesn't count)

**Comment by MattBrittan** [comment]
@alsm can you please clarify what you mean by "these only apply to the time spent waiting for a reply rather than the total time to run the function"? 

I would expect a `context.WithTimeout()` to expire after the specified period regardless of any other activity. In `publishQoS12` you pass the context into `c.serverInflight.Acquire` so I would expect that to exit, with an error, as soon as the context expires; this will cause `publishQoS12` to return an error. Apologies if I have overlooked something (running through this code for the first time - looks a lot tidier than the v3 library!).

**Comment by Tockra** [comment]
> There is no facility to check the connected status of the client, the API is designed as synchronous so if not connected Publish/etc. will return errors and there is an OnDisconnect callback for the client that is triggered if the server initiates a disconnect.

But then there is a internal connection state ? Otherwise I wouldn't understand what `KeepAlive` does. It is the time the client hold the current connection without active connection to the broker. 
And there is no way to find out if this connection is still connected or lost? So I need to add a own thread which trys to reconnect to the broker if some Publish in the past failed?

**Comment by justinclift** [comment]
@Tockra This bit seems relevant:

> ... there is an OnDisconnect callback for the client that is triggered if the server initiates a disconnect.

So, (guessing here) it'll just be that `OnDisconnect()` callback which does the reconnection.

**Comment by Tockra** [comment]
> Doesn't sound like you need a separate thread that tries to keep reconnecting?

That depends...
How fast does the client call onDisconnect after losing connection? Instantly after a Publish failed? 
In what thread / go routine runs ondisconnect. What happens when I add a infinite loop there?

**Comment by alsm** [comment]
> @alsm can you please clarify what you mean by "these only apply to the time spent waiting for a reply rather than the total time to run the function"?
> 
> I would expect a `context.WithTimeout()` to expire after the specified period regardless of any other activity. In `publishQoS12` you pass the context into `c.serverInflight.Acquire` so I would expect that to exit, with an error, as soon as the context expires; this will cause `publishQoS12` to return an error. Apologies if I have overlooked something (running through this code for the first time - looks a lot tidier than the v3 library!).
I may not have written that clearly, the WriteTo call that sends the data blocks and does not take a context, so potentially a call in the library could take longer than a timeout period to actually exit.
Also I'd like other thoughts on whether the contexts are actually useful. Having some way to signify now long a call should take an being able to abort is good, there is already support for the default value of PacketTimeout with the contexts, is a client wide value sufficient and should the context params be removed, or is the chance of it being beneficial worth having a lot of context.Backgrounds() being created and passed around? I'm more concerned with usability of the API than chasing down every last bit of performance.

> Sorry - adding a further question. "There is also a memory based persistence implemented, there is not currently a file based implementation" - I have searched through the package and cannot find any usage of the persistence interface (i.e. no calls to `Open()` or `Put()`. Is it up to the user to call these? Perhaps it would be worthwhile to have an example that includes reconnection and persistence; I believe that this would increase adoption of the new package (and I'm happy to work with you on this and look to improved the documentation at the same time).
:facepalm: I have written the bare implementation but not wired it up in the client.

**Comment by alsm** [comment]
> > Doesn't sound like you need a separate thread that tries to keep reconnecting?
> 
> That depends...
> How fast does the client call onDisconnect after losing connection? Instantly after a Publish failed?
> In what thread / go routine runs ondisconnect. What happens when I add a infinite loop there?
> I think onDisconnect will just called when the broker decide to disconnect your connection. Not when you lose your network connection.
> I just see a onDisconnect call in https://github.com/eclipse/paho.golang/blob/master/paho/client.go (incoming).

Yeah, I guess we need something like onConnectionLost that triggers on network errors. The problem with implementing autoreconnect as was done in the v3 client is that is the developers responsibility to obtain a network connection and pass it into the client. If that connection fails for some reason the client cannot recreate it. I don't intend to change this but the client can certainly be changed to work with a model whereby if the connection is lost the client remains in a state where you can call connect again with a new connection.

**Comment by Tockra** [comment]
I not really like the design pattern of using a own net.Conn.
Why should the user of your library learn other librarys to use yours? 
Isn't it the idea of a library to provide a abstraction of the underlying system? 
So you should build something, what hides the net.Conn and tls.Conn instead of giving that responsibility to the user.
I'm thinking the same about the contexts (but i dont know how normal the use of contexts is in go )...
Just my opinion...

**Comment by justinclift** [comment]
Heh Heh Heh.

It almost sounds like this needs a wrapper library, to provide the connection handling. :wink:

(That's **not** me volunteering to write such a thing.)

**Comment by alsm** [comment]
In the v3 client I let the dev provide a uri and tried to interpret that to open the right kind of connection, TCP, TLS, websocket, but that was a bit of a pain because there are different websocket libs. Or what if you want to use SCTP, or unix domain sockets, or wrap a pipe, or a channel, or buffer? If you just want a tcp socket it's going to be as easy for you to open it yourself and pass in the provided net.Conn, if you want to do something different you've got more flexibility to do that yourself than have the library abstract it.
Also it's much easier for my tests as I can just get a net.Pipe and pass it to the client.

I'm not against having a separate folder with helper functions if they're going to be useful; for example if you look in paho/extensions/rpc I've done a wrapper around a client to make RPC over mqtt5 simpler.

**Comment by MattBrittan** [comment]
**Contexts** - I utilise contexts for cancellation in almost all potentially long running functions that I write so am happy to see them used in this package (this makes a clean shutdown a lot simpler). A few calls to `context.Background()` is a small price for the flexibility that their inclusion provides (@Tockra: using contexts in this way is common in go applications; e.g.  `database/sql` uses this to allow for cancellation of queries).

**Connection** - I like the way a net.Conn is used (guess you could use an `io.ReadWriteCloser` as I dont think you are making any other calls). This removes a lot of complexity from the package and increases its flexibility (the v3 client has way to many options and many of them are connection related).

**Disconnects** - Will log a new issue re this because I think it deserves a seperate conversation.

>WriteTo call that sends the data blocks and does not take a context

I would like to see a `context` added to `WriteTo` for completeness (closing the connection is probably the best way to deal with a cancelled context when the write is in progress - not ideal but should be a fairly rare occurance). As I don't believe a `Deadline` is ever set there is the potential for a `Write` call to block for a long time (I guess the user could wrap the `net.Conn` to add their own Deadlines if required).

> I have written the bare implementation but not wired it up in the client.

I suspected that might be the case. I will raise a new issue for this so its clear to any new users that the functionality is not yet in place.

>It almost sounds like this needs a wrapper library, to provide the connection handling

The more I think about this the more I think that what is needed is an example rather than a wrapper (if we can get the `onConnectionLost` function right then connection management is actually pretty simple (so hiding it away in a package would be detremental to the readability of a users code).

**Comment by alsm** [comment]
> > WriteTo call that sends the data blocks and does not take a context
> 
> I would like to see a `context` added to `WriteTo` for completeness (closing the connection is probably the best way to deal with a cancelled context when the write is in progress - not ideal but should be a fairly rare occurance). As I don't believe a `Deadline` is ever set there is the potential for a `Write` call to block for a long time (I guess the user could wrap the `net.Conn` to add their own Deadlines if required).

This is one of those "I can't remember exactly why I did that" things but `WriteTo(w io.Writer) (n int64, err error)` is an interface function for `WriterTo` so can't extend it with contexts. Although if it's not giving us any benefit we can certainly revisit that.
