### ISSUE TITLE
I could not locate any alternative of mqtt.MessageHandler in this version. 

### ISSUE THREAD

**Issue by MT22067** [eclipse/paho.golang#250]
Just like in the paho.mqtt.golang we had this callback function: callback mqtt.MessageHandler
which was called whenever mesage was received from the broker.
Usage: func (mqtt.Client).Subscribe(topic string, qos byte, callback mqtt.MessageHandler) mqtt.Token
What is the alternatives of this in the current module?

**Comment by MattBrittan** [comment]
Please see [this example](https://github.com/eclipse/paho.golang/blob/master/autopaho/examples/basics/basics.go#L76). If you want a router then see [this](https://github.com/eclipse/paho.golang/blob/master/autopaho/examples/router/router.go#L64).

The approach in `paho.mqtt.golang` was not really ideal because when you connect and there are messages queued it's poaably for the client to receive the messages before it processes the `Publish` (meaning messages were lost).

**Comment by MT22067** [comment]
Thanks! 
Where can I read about what Router does?

**Comment by MT22067** [comment]
Thanks! @MattBrittan
