### ISSUE TITLE
module github.com/eclipse/paho.golang@latest found (v0.9.0), but does not contain package github.com/eclipse/paho.golang

### ISSUE THREAD

**Issue by tn185075** [eclipse/paho.golang#28]
**Describe the bug**
Error after executing go get on github.com/eclipse/paho.golang.

**To reproduce**
go get github.com/eclipse/paho.golang

**Debug output**
module github.com/eclipse/paho.golang@latest found (v0.9.0), but does not contain package github.com/eclipse/paho.golang

**Expected behaviour**
Not to show any package related error.

**Software used:**
- Go version 1.14.6 windows/amd64

**Comment by MattBrittan** [comment]
I have tested this with go 1.14.7 windows/amd64 (Windows 10) and was unable to duplicate. Running with modules enabled (e.g. `go mod init test`) successfully downloads the module; working outside of a module results in the error `can't load package: package github.com/eclipse/paho.golang: no Go files in C:\...\go\src\github.com\eclipse\paho.golang` (expected because there are no `.go` files in that folder in git).

Can you please confirm if you are using [Go Modules](https://blog.golang.org/using-go-modules) and provide the output from the `go env` command? If you are not using modules then you would need to `go get github.com/eclipse/paho.golang/paho` (that will get the package but I have not tried using this package outside of a module).

**Comment by tn185075** [comment]
Hey @MattBrittan I was using that with go modules.

Output of `go env`
![image](https://user-images.githubusercontent.com/68643107/89751405-8d3e5c00-daed-11ea-8767-e83388cd1acc.png)

I got this, when I tried to import it in a file. Until then my IDE didn't warn me anything.
![image](https://user-images.githubusercontent.com/68643107/89751471-d4c4e800-daed-11ea-9f0b-61d714f7e3b2.png)

**Comment by TarunNanduri** [comment]
Hey, I tried it on other machine. It's still the same.

**Comment by MattBrittan** [comment]
> Until then my IDE didn't warn me anything.

OK - it sounds like this warning is being produced by a linter used by your IDE (maybe gopls?). Can you please provide further details (i.e. what IDE) and also let us know the contents of the line it is referring to (I assume line 4 of `storage.go`).

To test this I created a project consisting of one .go file:

```
package main

import (
	"github.com/eclipse/paho.golang/paho"
)

func main() {
	_ = paho.NewClient()
}
```

I tested VSCode (with go Extension) and GoLand and neither reported any issues. I would be interested to know if your IDE does.

**Comment by tn185075** [comment]
Hey @MattBrittan , Thanks for letting me know. There's a mistake at my end. I haven't added /paho at the end while importing.

Can I know, why there's something to add again, instead of importing the same module. That made me confuse a bit.
I would also love if you can point out some usage references to this module. I can't find one on the internet.

Thanks for your time🙌.

**Comment by tn185075** [comment]
I didn't have a look on source, just got to know everything is done under paho package. Please do add that importing guidelines to README 👍

**Comment by MattBrittan** [comment]
Hi @tn185075 

>Can I know, why there's something to add again, instead of importing the same module. 

[Modules](https://blog.golang.org/using-go-modules) and [packages ](https://golang.org/ref/spec#Packages) are two different, but related, concepts.  A module (not actually part of the golang spec) and can contain 0-many packages. The `paho.golang`  package contains:

* `github.com/eclipse/paho.golang/paho` - The main package likely to be imported by a user.
* `github.com/eclipse/paho.golang/tree/master/paho/cmd/...` - A range of sample commands
* `github.com/eclipse/paho.golang/tree/master/paho/extensions/...` - Extensions to the paho package (currently only one)
* `github.com/eclipse/paho.golang/packets`  - Handles low level MQTT packet operations

I'm not sure why the decision was made to put the main package under `paho.golang/paho` rather than `paho.golang` but it does mean that the admin stuff (main `readme`, license, general documentation etc) is kept separate from the code which is nice.

>I would also love if you can point out some usage references to this module. I can't find one on the internet.

Check out [https://github.com/eclipse/paho.golang/tree/master/paho/cmd](https://github.com/eclipse/paho.golang/tree/master/paho/cmd) - there are a range of demos there. Please bear in mind that this is pre version 1 meaning some functionality is incomplete (see the open issue re persistence) and the API may change (but I would not expect any massive changes as it seems pretty well thought out).

**Comment by tn185075** [comment]
Thanks @MattBrittan . Will keep an eye on regular updates to this module.

Only one last thing to query, can we use this in production?

**Comment by MattBrittan** [comment]
> Only one last thing to query, can we use this in production?

That is really up to you (I have done some testing but am still using the older [github.com/eclipse/paho.mqtt.golang](https://github.com/eclipse/paho.mqtt.golang) in my production code (but that is due mainly to a lack of time and the lack of support for persistence & auto-reconnection in this package; both are being worked on).  I much prefer the way this newer package works; [this issue](https://github.com/eclipse/paho.golang/issues/23) has more info; specifically the comment from @alsm 

>I've just made some performance improvements today, but I believe the code to be fairly stable. But it hasn't had sufficient real world use to know that it won't need changing. If you were to use this client I would appreciate feedback on how it works/feels to use.

**Comment by tn185075** [comment]
Will have a look. Thanks
