### ISSUE TITLE
Request/Response pattern

### ISSUE THREAD

**Issue by jjm011** [eclipse/paho.golang#7]
Hi, 

Since the V5 MQTT now supports request/response using properties, can you please give me a brief example of how to use it with the new V5 go client?

Or is the function still not yet implemented?

Thanks!

**Comment by alsm** [comment]
The MQTT v5 spec has the extra properties in a publish; 'Response Topic' and 'Correlation Data'. The former being the topic you wish the remote endpoint to respond to your message on, the latter bring a free field you can use correlate the request and response if using the same response topic.

To send a Publish using these fields might look like this;
```golang
pb := &paho.Publish{
	Topic:   "topic/for/request/listener",
	QoS:     1, // whatever value you want (0,1,2)
	Payload: []byte(`{"request":"data"}`),
	
	Properties: &paho.PublishProperties{
		ResponseTopic: "my/response/topic",
		CorrelationData: []byte("<random stored string>"),
		ContentType:     "application/json", // you might want to set this if the remote listener takes different formats
	},
}

if _, err = c.Publish(context.Background(), pb); err != nil {
	log.Println(err)
}
```

This just send the message with the right fields set, you would still need to have subscribed to the topic you wish to receive your responses on and have a way to correlate the response with the requests (for example store the correlation data in a map when you send a request and look up against that data when you receive a response on your response topic).

This might be a feature where it would be useful to have an extension that you can optionally use with the client to make this simpler, without being a core part of the code.

**Comment by alsm** [comment]
I've just added an extension for Request/Response https://github.com/eclipse/paho.golang/tree/master/paho/extensions/rpc with a little example in https://github.com/eclipse/paho.golang/blob/master/paho/cmd/rpc/main.go it'd be good if you have the time to look over this and let me know what you think, is this the kind of thing you were thinking of? I've added it as an "extension" rather than part of the core for now as it might not be something everyone wants and seems to work (IMO) quite well like this.

**Comment by alsm** [comment]
I'll leave this open a couple more weeks incase there is any feedback otherwise I'll consider it done for now
