### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by cogitaria-admin** [eclipse/paho.golang#72]
Unfortunately this fails with "**no Go files**" error (with or without sudo): 

 _This client is designed to work with the standard Go tools, so installation is as easy as:_

**go get github.com/eclipse/paho.golang**

Easy yes, successful no. 

Also noted the client is wholly incompatible with paho.mqtt.golang client code.  Is that by design?

**Comment by alsm** [comment]
```

**Comment by alsm** [comment]
```
asm@ubuntu:~$ go get github.com/eclipse/paho.golang
go: downloading github.com/eclipse/paho.golang v0.9.0
```
Odd that it works for me, although the last released version is quite out of date now, as it seems to be currently stable I should do a new release.

On the API design and compatibility with the previous paho v3 client, yes that is by design. There were many aspects of that design that looking back I'm not happy with but I can't change them now, this v5 client was a chance to implement something having learned from that.
