### ISSUE TITLE
found that the message is not safe to write

### ISSUE THREAD

**Issue by imkos** [eclipse/paho.golang#81]
test code for reproduce:
```
client := NewMqClient(ub, auth)
client.df = JsonDataFormater{}
sr := loadServerP12Cert("obFm2pTw1kT8ADG7")
client.SetSecureRequst(envTestSrKid, sr)
obj := testObj{}
client.SubscribeRaw("****/p2p/consumerId@@@server09", obj)
num := uint32(0)
sem := semaphore.NewWeighted(80)
ctx := context.Background()
for {
  if err := sem.Acquire(ctx, 1); err != nil {
    t.Error("sem err,", err)
  }
  go func() {
    msgId := atomic.AddUint32(&num, 1)
    src := []byte(fmt.Sprintf(`{"msgType":"get","fromId":"server09","fromType":2,"msgId":%d,"msgDate":1637635559,"services":{"pluginsharealbum_create":{"share_key":"90a87a21785c4af28bd07fc76d077264","url":"http://127.0.0.1:8070?shareKey=90a87a21785c4af28bd07fc76d077264","name":"9","cover_path":"/6B653C174CCFAB6DD62A73DC3FD594C9/.HOMES/18665875540/00/IMG_20210812_112814.jpg","kid":"3033417224"}},"routePath":"cloud_interal"}`, msgId))
    client.PublishRaw("****/p2p/consumerId@@@hy_noid_000000000056/agent", nil, src)
    sem.Release(1)
  }()
}
```
```
 >20 Concurrent publish message, client disconnected
```

server requested disconnect (reason: 129)
server requested disconnect: &{ServerReference: ReasonString: SessionExpiryInterval:<nil> User:[]}
connection to broker lost (server requested disconnect (reason: 129)); will reconnect
Problems caused by NOACK

[warning] server09@****:7266 [Channel] The PUBACK PacketId 12987 is not found.

It appears that the mqtt broker repeatedly sends the same message to the client, and there has been no ack, causing the server to disconnect the connection

server error message:
```
2021-11-24T11:34:07.411614+08:00 [error] deviceAgent-hy_noid_000000000056@120.234.47.82:52542 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_utf8_string,[<<50,201,1,0,36,100,109,95,97,105,114,100,105,115,107,47,112,50,112,47,99,111,110,115,117,109,101,114,73,100,64,64,64,115,101,114,118,101,114,48,57,0,12,2,1,0,123,34,101,114,114,111,114,95,99,111,100,101,34,58,48,44,34,109,115,103,84,121,112,101,34,58,34,103,101,116,82,101,115,112,34,44,34,102,114,111,109,73,100,34,58,34,104,121,...>>],[{file,"emqx_frame.erl"},{line,464}]},{emqx_frame,parse_packet,3,[{file,"emqx_frame.erl"},{line,249}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,183}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<50,201,1,50,201,1,0,36,100,109,95,97,105,114,100,105,115,107,47,112,50,112,47,99,111,110,115,117,109,101,114,73,100,64,64,64,115,101,114,118,101,114,48,57,0,12,2,1,0,123,34,101,114,114,111,114,95,99,111,100,101,34,58,48,44,34,109,115,103,84,121,112,101,34,58,34,103,101,116,82,101,115,112,34,44,34,102,114,111,109,73,100,34,58,34,104,121,95,110,...>>
2021-11-24T11:34:08.013642+08:00 [error] deviceAgent-hy_noid_000000000056@120.234.47.82:52548 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_utf8_string,[<<"\"services\":{\"pluginsharealbum_create\":null}}">>],[{file,"emqx_frame.erl"},{line,464}]},{emqx_frame,parse_packet,3,[{file,"emqx_frame.erl"},{line,249}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,183}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<"7,\"services\":{\"pluginsharealbum_create\":null}}{\"error_code\":0,\"msgType\":\"getResp\",\"fromId\":\"hy_noid_000000000056\",\"fromType\":0,\"msgId\":840,\"msgDate\":1637724847,\"services\":{\"pluginsharealbum_create\":null}}2�"...>>
```

found message data sticky packets, Frame data error.

![image](https://user-images.githubusercontent.com/17872894/143183795-56aaf8ba-d8d9-4205-a33a-50e9d5b42bf0.png)

OR 
```
// Packets WriterTo
whatWriteTo struct {
  w io.WriterTo
  e error
}

Client struct {
  mu sync.Mutex
  ClientConfig
  // raCtx is used for handling the MQTTv5 authentication exchange.
  raCtx          *CPContext
  stop           chan struct{}
  publishPackets chan *packets.Publish
  acksTracker    acksTracker
  workers        sync.WaitGroup
  serverProps    CommsProperties
  clientProps    CommsProperties
  serverInflight *semaphore.Weighted
  clientInflight *semaphore.Weighted
  debug          Logger
  errors         Logger
  outPackets     chan *whatWriteTo
}
```
newClient:
```
// new zero size chan for block
&Client{
  outPackets: make(chan *whatWriteTo),
}
go waitWrite()
```

add sub func:
```
func (c *Client) waitWrite() {
	for {
		wwt, ok := <-c.outPackets
		if !ok {
			return
		}
		_, wwt.e = wwt.w.WriteTo(c.Conn)
	}
}

func (c *Client) doWrite(sp io.WriterTo) error {
	wt := &whatWriteTo{
		w: sp,
	}
	c.outPackets <- wt
	return wt.e
}
```
Client object  sub function `*.WriteTo(c.Conn)`  to  `c.doWrite(*)`

**Comment by thejan2009** [comment]
`ControlPacket` in package packets is not thread-safe for writing because it invokes `io.Write` multiple times.

It can happen that multiple control packets will be written to `net.Conn` simultaneously, producing an incorrect, mixed up packet. The same problem can happen with `FixedHeader`, too. Issues might be observed when multiple messages are published concurrently, but a potential incorrect packet can happen even when publishing a single message if `PingHandler` writes the `PINGREQ` at the same time.

I've been thinking how it could be fixed, but there seem to be no obvious solutions without drawbacks:
 - Optimally a mutex would be provided to ControlPacket so it could lock it right before writing to `net.Conn`.  This would require `packets` API changes, may be breaking and unwanted.
 - Add a mutex to `mqtt.Client` and lock before writing any packet to `net.Conn`. Compared to above, it's simpler to implement, there are no breaking changes in packets package, but there is a performance impact given that we spend additional time being locked while a packet is preparing ControlPacket and then creating buffers and finally writing them to `net.Conn`.
The above can also be implemented with goroutines and channels, but the Write operations will be blocking, so I don't see any advantages.

@alsm @MattBrittan what would be the preferred method of solving this?

**Comment by MattBrittan** [comment]
@thejan2009 sorry - @alsm generally handles most things regarding this repo but as he has not replied I will.

The example in your initial "code for reproduce" uses functions not in `paho.golang` (e.g. `client.PublishRaw`) which makes it difficult to fully understand your issue. If I understand you correctly you are raising an issue with the fact that the following calls `w.Write` twice?

```go
func (f *FixedHeader) WriteTo(w io.Writer) (int64, error) {
	if _, err := w.Write([]byte{byte(f.Type)<<4 | f.Flags}); err != nil {
		return 0, err
	}
	if _, err := w.Write(encodeVBI(f.remainingLength)); err != nil {
		return 0, err
	}
	return 0, nil
}
```
This could be an issue if `WriteTo` is called concurrently and passed the same `io.Writer`. However, based on a quick look through the code, I don't think that happens. The `FixedHeader` is always part of another packet and writes go into a buffer e.g.

```go 
// WriteTo writes a packet to an io.Writer, handling packing all the parts of
// a control packet.
func (c *ControlPacket) WriteTo(w io.Writer) (int64, error) {
	buffers := c.Content.Buffers()
	for _, b := range buffers {
		c.remainingLength += len(b)
	}

	var header bytes.Buffer
	if _, err := c.FixedHeader.WriteTo(&header); err != nil {
		return 0, err
	}

	buffers = append(net.Buffers{header.Bytes()}, buffers...)

	return buffers.WriteTo(w)
}
```

So this is using `c.FixedHeader.WriteTo` but the write is into a buffer created specifically for the purpose. The result is then combined with `buffers` before being written out (so one write to the `io.Reader` passed in).

Based on a quick run-through I cannot spot the issue you are seeking to address; note that I am not all that familiar with this code (I still use the v3.11 library) so may well be missing something (or you may be using the functions in an unexpected way). Can you please provide a full example (a test would be ideal).

*Note: Your pull request is likely to be ignored until you have signed the ECA because we cannot accept it without that agreement being in place.*

**Comment by thejan2009** [comment]
Hi, thank you for the prompt response, note that I'm not the original issue submitter.

Given its usage, `FixedHeader` seems ok, seems I extrapolated the issue a bit too far, sorry about that.

There is a race condition when writing `ControlPacket`s to `net.Conn` because there is no control over who's writing. For example, if two goroutines publish at the same time, their ControlPackets might get mixed up. I noticed this issue in a resource-constrained environment when I somehow published a message at the same time as PingHandler made a `PINGREQ`. Since there's strict packet validation on the server, my client was disconnected immediately.

A test that reproduces the issue: extended `packets/packets_test.go` with two benchmarks, the only difference is `sync.Mutex` usage in the second one, which is in line with the second proposed solution from my previous comment. The reader goroutine reads packets and there are 10 goroutines writing to `io.Pipe`. If the writes are not coordinated with a lock, they become mixed up. This is because `net.Buffers` is a `[][]byte` and its `WriteTo` method calls `io.Write` in a for loop - when `io.Write` is not being executed, this is an opportunity for another goroutine to start writing its packet.

```go
func BenchmarkWriteTo(b *testing.B) {
	x := NewControlPacket(PUBLISH)
	x.Content.(*Publish).QoS = 0
	x.Content.(*Publish).Topic = "testTopic"
	x.Content.(*Publish).PacketID = uint16(100)
	x.Content.(*Publish).Payload = []byte("testPayload")
	pp := x.Content.(*Publish)

	r, w := io.Pipe()

	var wg sync.WaitGroup

	done := make(chan int, 1)
	go func(r io.Reader, done chan int) {
		for {
			_, err := ReadPacket(r)
			if err != nil {
				b.Error(err)
			}

			select {
			case <-done:
				return
			default:
			}
		}
	}(r, done)

	for i := 0; i < 10; i++ {
		wg.Add(1)
		go func() {
			for n := 0; n < b.N; n++ {
				pp.WriteTo(w)
			}
			wg.Done()
		}()
	}

	wg.Wait()
	done <- 1
}

func BenchmarkWriteTo_Mutex(b *testing.B) {
	x := NewControlPacket(PUBLISH)
	x.Content.(*Publish).QoS = 0
	x.Content.(*Publish).Topic = "testTopic"
	x.Content.(*Publish).PacketID = uint16(100)
	x.Content.(*Publish).Payload = []byte("testPayload")
	pp := x.Content.(*Publish)

	r, w := io.Pipe()

	var wg sync.WaitGroup
	done := make(chan int, 1)

	go func(r io.Reader, done chan int) {
		for {
			_, err := ReadPacket(r)
			if err != nil {
				b.Error(err)
			}

			select {
			case <-done:
				return
			default:
			}
		}
	}(r, done)

	var mu sync.Mutex
	for i := 0; i < 10; i++ {
		wg.Add(1)
		go func() {
			for n := 0; n < b.N; n++ {
				mu.Lock()
				pp.WriteTo(w)
				mu.Unlock()
			}
			wg.Done()
		}()
	}

	wg.Wait()
	done <- 1
}
```

Gives the following output (shortened):
```
[~/git/paho.golang/packets] go test -bench 'BenchmarkWriteTo(_Locked)?'
goos: darwin
goarch: arm64
pkg: github.com/eclipse/paho.golang/packets
BenchmarkWriteTo-8              --- FAIL: BenchmarkWriteTo-8
    packets_test.go:445: EOF
    packets_test.go:445: invalid Prop type 0 for packet 4
    packets_test.go:445: invalid Prop type 101 for packet 4
    packets_test.go:445: invalid Prop type 116 for packet 4
    packets_test.go:445: unknown packet type 0 requested
.
.
.
    packets_test.go:445: invalid Prop type 105 for packet 4
    packets_test.go:445: invalid Prop type 115 for packet 4
    packets_test.go:445: invalid Prop type 48 for packet 4
    packets_test.go:445: unknown packet type 0 requested
    packets_test.go:445: invalid Prop type 112 for packet 4
    packets_test.go:445: invalid Prop type 48 for packet 4
    packets_test.go:445: invalid Prop type 48 for packet 4
    packets_test.go:445: unknown packet type 0 requested
    packets_test.go:445: invalid Prop type 112 for packet 4
    packets_test.go:445: invalid Prop type 0 for packet 4
    packets_test.go:445: invalid Prop type 23 for packet 4
BenchmarkWriteTo_Mutex-8           27843             42121 ns/op
FAIL
exit status 1
FAIL    github.com/eclipse/paho.golang/packets  1.788s
```

**Comment by alsm** [comment]
What platform and what net.Conn are you using for this? This is might be true if you're using something like an io.Pipe but writeTo in net.Buffers on Writers that support writev is designed to support writing from multiple buffers in one go https://linux.die.net/man/2/writev
additionally a net.Conn is she to be written to from multiple goroutines [concurrently](https://cs.opensource.google/go/go/+/refs/tags/go1.17.8:src/net/net.go;l=112)

**Comment by thejan2009** [comment]
I'm using `tls.Conn` from stdlib. That does not seem to support `writev`, or did I miss anything?

**Comment by thejan2009** [comment]
This might be relevant: https://github.com/golang/go/issues/27203#issuecomment-844072158

**Comment by MattBrittan** [comment]
@thejan2009 - thanks for the tests. However your code is creating a single `Publish` packet and then concurrently calling `WriteTo` on that. The fact that this fails is unsurprising; the code does not support concurrent access to a single `Packet` instance. Note: I'm not saying that there is not an issue but your test WILL show an issue because it leads to race conditions within the single packet instance.

As you mention `buffers.WriteTo` could well be an issue:

```
// buffersWriter is the interface implemented by Conns that support a
// "writev"-like batch write optimization.
// writeBuffers should fully consume and write all chunks from the
// provided Buffers, else it should report a non-nil error.
type buffersWriter interface {
	writeBuffers(*Buffers) (int64, error)
}

func (v *Buffers) WriteTo(w io.Writer) (n int64, err error) {
	if wv, ok := w.(buffersWriter); ok {
		return wv.writeBuffers(v)
	}
	for _, b := range *v {
		nb, err := w.Write(b)
		n += int64(nb)
		if err != nil {
			v.consume(n)
			return n, err
		}
	}
	v.consume(n)
	return n, nil
}
```

So if `w` is a `buffersWriter` then this is likely to be OK ("buffersWriter is the interface implemented by Conns that support a "writev"-like batch write optimization") but the docs do not say this explicitly. However a `tls.Conn` is NOT a `buffersWriter` so the fact that the above will make multiple calls to `w.Write` is an issue.

**Comment by thejan2009** [comment]
I've moved ControlPacket creation inside the loops but there was no improvement.

Also a reproduction of the issue based on authopaho/examples/docker: https://github.com/thejan2009/paho.golang/commits/packets-writeto

A few toggles were added to `docker-compose.yml` allowing you to toggle publisher connection via TLS or TCP, and lock a mutex when publishing a message. If anybody runs this, notice the publisher will get disconnected in various ways with TLS enabled and locks disabled, e.g. mosquitto reporting "docker-mosquitto-1  | 2022-03-06T10:38:08: Client mqtt_publisher disconnected due to protocol error."

**Comment by MattBrittan** [comment]
Another relevant go issue is [21676 - net: Buffers makes multiple Write calls on Writers that don't implement buffersWriter](https://github.com/golang/go/issues/21676).

Solving this within `packets`, whilst continuing to use `net.Buffers`, will be difficult because `net.writeBuffers` is unexported so we cannot call this ourselves (or even check if the `io.Writer` implements it).

So a few potential solutions:

* Combine the buffers and just call `Write` ; this will significantly increase allocations but is the simplest option. This should be safe as the `io.Writer` is a `net.Conn` (from `ClientConfig`) and `net.Conn` guarantees "Multiple goroutines may invoke methods on a Conn simultaneously" (`io.Writer` does not guarantee this so worth noting the restriction in `packets`).
* Use a `Mutex` in `paho` to prevent concurrent calls.

**Comment by thejan2009** [comment]
An extension of the second option would be extending `Packet` interface:
```go
	Packet interface {
		Unpack(*bytes.Buffer) error
		Buffers() net.Buffers
		WriteTo(io.Writer) (int64, error)
		AtomicWriteTo(*sync.Mutex, io.Writer) (int64, error)
	}
	
// AtomicWriteTo does a thread-safe write of a packet to an io.Writer
func (c *ControlPacket) AtomicWriteTo(mu *sync.Mutex, w io.Writer) (int64, error) {
	buffers := c.Content.Buffers()
	for _, b := range buffers {
		c.remainingLength += len(b)
	}

	var header bytes.Buffer
	if _, err := c.FixedHeader.WriteTo(&header); err != nil {
		return 0, err
	}

	buffers = append(net.Buffers{header.Bytes()}, buffers...)

	mu.Lock()
	defer mu.Unlock()
	return buffers.WriteTo(w)
}

```
